### ISSUE TITLE
Textual issue in privacy statement (NL)

### ISSUE THREAD

**Issue by herkocoomans** [minvws/nl-covid19-notification-app-design#89] opened 2020-08-17 08:33 UTC
### Textual issue in privacy statement (NL)

1. Go to 'Over de app'
2. Scroll down to 'Privacyverklaring'
3. Scroll down to '6. Aan wie worden persoonsgegevens verstrekt?'

First sentence in first paragraph starts with 'HeHet'. This should be 'Het'

 - OS: iOS 13.6
 - Version 1.0.2.(68559-89543ff)

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by jorisleker** [comment] 2020-08-21 07:39
Duplicate of https://github.com/minvws/nl-covid19-notification-app-website/issues/251

**Closed by jorisleker** 2020-08-21 07:39 UTC
Labels: duplicate
